name: observable
version: 0.20.5
author: Dart Team <misc@dartlang.org>
description: Support for marking objects as observable
homepage: https://github.com/dart-lang/observable
environment:
  sdk: '>=1.22.0-dev <2.0.0'
dependencies:
  collection: '^1.11.0'
  meta: '^1.0.4'
  quiver: '^0.24.0'
dev_dependencies:
  dart_style: '^0.2.0'
  test: '^0.12.17'
